// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function TestComponent(props) {
  return JsxRuntime.jsx("div", {
              children: "Test component. Try changing this text. Component should fast refresh, and counter value should remain unchanged."
            });
}

var make = TestComponent;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
